[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.25'
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.ci]
fuzz_runs = 1000
verbosity = 4

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
localhost = "http://localhost:8545"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
holesky = "https://ethereum-holesky.blockpi.network/v1/rpc/public"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true 